Punishments:
  CancelEvent: true
  RemoveItem: false
  ReduceHealthPercentage: 20
  ReduceHealth: 0
  Commands: []

PunishmentVisual:
  Lightning: true
  Firework: true
  PlaySound: true

Alerts:
  Enable: true
  SendEvery: 10
  AlertMessage: "<player> is holding <owner>'s <item>"

BlockMessage:
  Enable: true
  SendEvery: 10
  BlockMessage: "Hey! You cannot use <owner>'s <item>"

Message:
  Prefix: "&7[&6ISN&7] &r"
  noPermission: "&cYou do not have permission to perform this command!"
  serialNotFound: "&cSerial Number Not Found from this item"
  successRegister: "&aSuccessfully Registered this Item to SerialCommand System!"
  successUnregister: "&cSuccessfully Unregistered this Item from SerialCommand System!"
  failedToUnregister: "&cFailed to Unregister this Item from SerialCommand System! \nBecause it was set to prevent unRegistration"
  itemAlreadyHaveSerial: "&cThis item already have Serial Number!"
  commandCanOnlySendByPlayer: "&cThis Command can only be sent by player!"
  #available placeholder:
  #<item> - item's name
  #<owner> - owner's name
  #<owner UUID> - owner's UUID
  #<holder> - holder's name
  #<holder UUID> - holder's UUID
  #<register time> - Register time in UNIX
  #<register date> - Register Date
  #<serial> - SerialCommand ID
  #<canUnlock> - return canUnlock attribute
  #<allowPunishment> - return allow Punishment attribute
  #<alerts> - return Alerts attribute
  ItemInfo-Admin:
    - "&7Item Info of &e<item>"
    - "&7"
    - "&7Owner: &e<owner> &8(<owner UUID>)"
    - "&7Last Holder: &e<holder> &8(<holder UUID>)"
    - "&7Register Time: &e<register date> &8(<register time>)"
    - "&7Serial ID: &b<serial>"
    - "&7"
    - "Attributes:"
    - " &7- Can Unlock: &d<canUnlock>"
    - " &7- Allow Punishment: &d<allowPunishment>"
    - " &7- Alerts: &d<alerts>"
    ItemInfo-Default:
      - "&7Item Info of &e<item>"
      - "&7"
      - "&7Owner: &e<owner>"

#to make item register to ISN add this to it's NBT:
# - ISN <Boolean>|<Boolean>|<Boolean> = make item automatically registered to ISN
# - First Boolean is can Unlock via normal unlock command (true = Allow normal unlock command to unlock)
# - Second Boolean is for can punish (true = Allow Punishment)
# - Third Boolean is for allow Alerts and Block Message (true = Allow Alert and Block Message)
# - to make item that prevents player from giving it to others just use false|true|true